use super::*;

pub(super) fn append_symbol_lifetime(output: &mut TranslationUnit) {
    append_function(
        output,
        FunctionSignature::new(
            "MalType_Symbol",
            "mal_symbol_retain",
            [
                context_parameter(),
                Parameter::named("MalType_Symbol", "value"),
            ],
        ),
        Block::new([
            Statement::expression(Expr::named_call(
                "mal_retain",
                [
                    Expr::identifier("context"),
                    Expr::identifier("value").field("ownership"),
                ],
            )),
            Statement::return_value(Expr::identifier("value")),
        ]),
    );
    append_function(
        output,
        FunctionSignature::static_inline(
            "void",
            "mal_symbol_release",
            [Parameter::named("MalType_Symbol", "value")],
        ),
        Block::new([Statement::if_then(
            Expr::not_equal(
                Expr::identifier("value").field("ownership"),
                Expr::identifier("NULL"),
            ),
            Block::new([Statement::if_then(
                Expr::not_equal(
                    Expr::named_call(
                        "mal_release",
                        [Expr::identifier("value").field("ownership")],
                    ),
                    uint8(0),
                ),
                Block::new([
                    Statement::if_then(
                        Expr::equal(
                            allocation_for(Expr::identifier("value").field("ownership"))
                                .pointer_field("capacity"),
                            Expr::identifier("SIZE_MAX"),
                        ),
                        Block::new([
                            Statement::variable(
                                TypeName::named("MalSymbolRope").pointer(),
                                "rope",
                                Some(Expr::cast(
                                    TypeName::named("MalSymbolRope").pointer(),
                                    Expr::identifier("value").field("ownership"),
                                )),
                            ),
                            Statement::call(
                                "mal_symbol_release",
                                [Expr::identifier("rope").pointer_field("right")],
                            ),
                            Statement::call(
                                "mal_symbol_release",
                                [Expr::identifier("rope").pointer_field("left")],
                            ),
                            Statement::if_then(
                                Expr::not_equal(
                                    Expr::identifier("rope").pointer_field("flattened"),
                                    Expr::identifier("NULL"),
                                ),
                                Block::new([Statement::call(
                                    "mal_deallocate",
                                    [Expr::identifier("rope").pointer_field("flattened")],
                                )]),
                            ),
                        ]),
                    ),
                    Statement::call(
                        "mal_deallocate",
                        [Expr::identifier("value").field("ownership")],
                    ),
                ]),
            )]),
        )]),
    );
}

pub(super) fn append_host_symbol_lifetime(output: &mut TranslationUnit) {
    append_function(
        output,
        FunctionSignature::new(
            "MalType_Symbol",
            "mal_Symbol_clone",
            [
                context_parameter(),
                Parameter::named("MalType_Symbol", "value"),
            ],
        ),
        Block::new([Statement::return_value(Expr::named_call(
            "mal_symbol_retain",
            [Expr::identifier("context"), Expr::identifier("value")],
        ))]),
    );
    append_function(
        output,
        FunctionSignature::new(
            "MalType_Symbol",
            "mal_Symbol_take",
            [Parameter::named(
                TypeName::named("MalType_Symbol").pointer(),
                "value",
            )],
        ),
        Block::new([
            Statement::variable(
                "MalType_Symbol",
                "result",
                Some(Expr::dereference(Expr::identifier("value"))),
            ),
            Statement::assignment(
                Expr::dereference(Expr::identifier("value")),
                symbol([
                    Expr::identifier("NULL"),
                    uint64(0),
                    Expr::identifier("NULL"),
                ]),
            ),
            Statement::return_value(Expr::identifier("result")),
        ]),
    );
    append_function(
        output,
        FunctionSignature::new(
            "void",
            "mal_Symbol_drop",
            [
                context_parameter(),
                Parameter::named(TypeName::named("MalType_Symbol").pointer(), "value"),
            ],
        ),
        Block::new([
            Statement::expression(Expr::cast("void", Expr::identifier("context"))),
            Statement::call(
                "mal_symbol_release",
                [Expr::dereference(Expr::identifier("value"))],
            ),
            Statement::assignment(
                Expr::dereference(Expr::identifier("value")),
                symbol([
                    Expr::identifier("NULL"),
                    uint64(0),
                    Expr::identifier("NULL"),
                ]),
            ),
        ]),
    );
}
