//! Kind constraints generated by one resolved type expression.

use std::collections::HashMap;

use mal_syntax::ast::Node;
use mal_syntax::diagnostic::Diagnostic;

use crate::resolve::ast::{BUFFER_TYPE, TypeExpression, TypeId};

use super::super::expand::predefined_type;
use super::Kinds;
use super::solver::{InferredKind, Solver};

impl Kinds {
    pub(super) fn infer_expression(
        &self,
        expression: &Node<TypeExpression>,
        locals: &HashMap<TypeId, InferredKind>,
        component: &HashMap<TypeId, InferredKind>,
        solver: &mut Solver,
    ) -> Result<InferredKind, Diagnostic> {
        match &expression.kind {
            TypeExpression::Named(reference) => {
                self.reference(reference.id, locals, component, solver, reference.name.span)
            }
            TypeExpression::Application {
                constructor,
                arguments,
            } => {
                let mut result = self.reference(
                    constructor.id,
                    locals,
                    component,
                    solver,
                    constructor.name.span,
                )?;
                for argument in arguments {
                    let argument_kind =
                        self.infer_expression(argument, locals, component, solver)?;
                    let next = solver.fresh();
                    solver.unify(
                        result,
                        Solver::function(argument_kind, next.clone()),
                        argument.span,
                    )?;
                    result = next;
                }
                Ok(result)
            }
            TypeExpression::Unit => Ok(InferredKind::Type),
            TypeExpression::Parenthesized(inner) => {
                self.infer_expression(inner, locals, component, solver)
            }
            TypeExpression::Product(elements) | TypeExpression::Sum(elements) => {
                for element in elements {
                    let kind = self.infer_expression(element, locals, component, solver)?;
                    solver.unify(kind, InferredKind::Type, element.span)?;
                }
                Ok(InferredKind::Type)
            }
            TypeExpression::Function { parameter, result } => {
                for part in [parameter.as_ref(), result.as_ref()] {
                    let kind = self.infer_expression(part, locals, component, solver)?;
                    solver.unify(kind, InferredKind::Type, part.span)?;
                }
                Ok(InferredKind::Type)
            }
        }
    }

    fn reference(
        &self,
        id: TypeId,
        locals: &HashMap<TypeId, InferredKind>,
        component: &HashMap<TypeId, InferredKind>,
        solver: &mut Solver,
        span: mal_syntax::source::Span,
    ) -> Result<InferredKind, Diagnostic> {
        if let Some(kind) = locals.get(&id).or_else(|| component.get(&id)) {
            return Ok(kind.clone());
        }
        if id == BUFFER_TYPE {
            return Ok(Solver::function(InferredKind::Type, InferredKind::Type));
        }
        if let Some(kind) = self.declarations.get(&id) {
            return Ok(solver.instantiate(kind));
        }
        if predefined_type(id).is_some() {
            return Ok(InferredKind::Type);
        }
        Err(Diagnostic::error("type has no inferred kind")
            .with_primary(span, "this type declaration is unavailable"))
    }
}
