[package]
name = "mal-fmt"
version.workspace = true
edition.workspace = true
description = "Formatter for the mal language"
license.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "mal-fmt"
path = "src/main.rs"

[dependencies]
mal-syntax = { path = "../mal-syntax" }

[dev-dependencies]
mal-frontend = { path = "../mal-frontend" }

[lints]
workspace = true
