[package]
name = "mal-backend"
version.workspace = true
edition.workspace = true
description = "Lowering, execution planning, and LLVM and C generation for the mal language"
license.workspace = true
publish.workspace = true

[dependencies]
mal-frontend = { path = "../mal-frontend" }
mal-syntax = { path = "../mal-syntax" }

[lints]
workspace = true
